name: 'Treeware'
description: 'Generates a categorized changelog and releases your prod or beta.'
author: 'tronku'
branding:
  icon: 'box'
  color: 'blue'

inputs:
  drafter_path: 
    description: 'Path to the drafter file'
    required: false
    default: drafter.yml

  prod_branch:
    description: 'Production branch of the repo'
    required: false
    default: ''

  should_release:
    description: 'Should release a new version?'
    required: false
    default: 'false'
  
  version_name:
    description: 'Version name of the upcoming release'
    required: false
    default: ''

  is_beta:
    description: 'Is this a beta release?'
    required: false
    default: 'false'

  beta_branch:
    description: 'Beta branch of the repo for release'
    required: false
    default: ''

  assets:
    description: 'Path to the assets, separated by comma'
    required: false
    default: ''

  target_commitish:
    description: 'Specifies the commitish value that determines where the Git tag is created from. Can be any branch or commit SHA.'
    default: ''
    required: false

  is_prerelease:
    description: 'Is this a prerelease?'
    default: 'false'
    required: false
  
  is_draft:
    description: 'Is this just a draft of the release?'
    default: 'false'
    required: false
  
  extra_release_note:
    description: 'Extra note to add in the GitHub release notes'
    default: ''
    required: false

  slack_workspace_id:
    description: 'Slack workspace ID for communication'
    default: ''
    required: false

  slack_channel_id:
    description: 'Slack channel ID for communication'
    default: ''
    required: false

  slack_webhook_id:
    description: 'Slack webhook ID for communication'
    default: ''
    required: false

  title_observer_section:
    description: 'Section that needs to be used for title in changelogs, by default it uses PR title'
    default: ''
    required: false

  ignore_changelogs:
    description: 'To ignore changelogs and only release on Github'
    default: 'false'
    required: false

outputs:
  changelogs:
    description: 'Categorized changelogs based on labels'

  upload_url:
    description: 'The assets upload URL to the GitHub release'

  release_url:
    description: 'The URL to the GitHub release'  

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.prod_branch }}
    - ${{ inputs.drafter_path }}
    - ${{ inputs.should_release }}
    - ${{ inputs.is_beta }}
    - ${{ inputs.beta_branch }}
    - ${{ inputs.version_name }}
    - ${{ inputs.assets }}
    - ${{ inputs.target_commitish }} 
    - ${{ inputs.is_prerelease }}
    - ${{ inputs.is_draft }}
    - ${{ inputs.extra_release_note }}
    - ${{ inputs.slack_workspace_id }}
    - ${{ inputs.slack_channel_id }}
    - ${{ inputs.slack_webhook_id }}
    - ${{ inputs.title_observer_section }}
    - ${{ inputs.ignore_changelogs }}